# Generated by Django 5.1.2 on 2025-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_teachingsession_current_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachingsession',
            name='guide_index',
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='guide_key',
            field=models.CharField(default='Guide1', max_length=30),
        ),
    ]
