# Generated by Django 5.1.2 on 2025-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_teachingsession_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingsession',
            name='user_name',
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='user_account_id',
            field=models.CharField(default='123', max_length=20),
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='user_account_name',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
