# Generated by Django 5.1.2 on 2024-12-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_teachingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingsession',
            name='guide_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='question_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
