# Generated by Django 5.1.2 on 2025-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userauth_remove_teachingsession_guide_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingsession',
            name='user_name',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
