# Generated by Django 5.1 on 2025-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_teachingsession_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingsession',
            name='all_fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='last_user_situation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='origin_user_situation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teachingsession',
            name='topic_fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teachingsession',
            name='user_account_id',
            field=models.CharField(max_length=20),
        ),
    ]
